services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    SolidInvoice\MoneyBundle\Form\Type\HiddenMoneyType: ~

    SolidInvoice\MoneyBundle\Form\Type\CurrencyType:
        arguments:
            $locale: '%env(locale)%'
