# https://packager.io/documentation/customizing-the-build/

name: blah
user: "apache"
group: "apache"
buildpack: https://github.com/heroku/heroku-buildpack-php.git#master
env:
  - STACK=cedar

targets:
  centos-7:
    build_dependencies:
      - readline
      - readline-devel
    dependencies:
      - mysql
      - php-twig-ctwig
#  debian-7:
#    - libreadline5
#    - libreadline-dev
#  ubuntu-14.04:
#    - libreadline5
#    - libreadline-dev

# turn off emails for now
notifications: false

# Build and protect (this is before distribution)
# https://packager.io/documentation/customizing-the-build/#before\
