buildpack: https://github.com/pierredup/heroku-buildpack-php

targets:
  centos-6:
    build_dependencies:
      - python2.7
      - readline
      - readline-devel
    dependencies:
      - mysql
      - php-twig-ctwig
      
before:
    - yum update -y
    - python --version
    - which python
    - ls -la /usr/bin
    - ls -la /usr/local/bin

notifications: false
