# https://packager.io/documentation/customizing-the-build/

name: CSBill
user: "apache"
group: "apache"
buildpack: "https://github.com/pierredup/packager-buildpack-php"
  
build_dependencies:
  - libmcrypt
  - libmcrypt-devel
  - readline
  - readline-devel
  
#before:
    - mkdir -p $HOME/bin
    - curl "http://packager-php.s3.amazonaws.com/jq/jq" -L -s -o - > "$HOME/bin/jq"
    
#targets:
  #centos-7: ~
#  debian-7:
#    - libreadline5
#    - libreadline-dev
#  ubuntu-14.04:
#    - libreadline5
#    - libreadline-dev
# turn off emails for now
notifications: false

# Build and protect (this is before distribution)
# https://packager.io/documentation/customizing-the-build/#before\
