buildpack: https://github.com/pierredup/heroku-buildpack-php

targets:
  centos-6:
    build_dependencies:
      - readline
      - readline-devel
      - python-pip
      - python-setuptools
      - python-bob-builder
    dependencies:
      - mysql
      - php-twig-ctwig

after:
    - cat /home/pkgr/.pip/pip.log
