services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: twig.extension }

    SolidInvoice\CoreBundle\Twig\Extension\GlobalExtension:
        arguments:
            $installed: '%env(installed)%'

    SolidInvoice\CoreBundle\Twig\Extension\BillingExtension: ~

    SolidInvoice\CoreBundle\Twig\Extension\FileExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'

    SolidInvoice\CoreBundle\Twig\Extension\StatusExtension: ~
    SolidInvoice\CoreBundle\Twig\Extension\SerializerExtension: ~
    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text
