_install_check_requirements:
    path: /install
    defaults: { _controller: SolidInvoice\InstallBundle\Action\SystemRequirements }

_install_config:
    path: /install/config
    defaults: { _controller: SolidInvoice\InstallBundle\Action\Config }

_install_install:
    path: /install/install
    defaults: { _controller: SolidInvoice\InstallBundle\Action\Install }
    options:
        expose: true

_install_setup:
    path: /install/setup
    defaults: { _controller: SolidInvoice\InstallBundle\Action\Setup }

_install_finish:
    path: /install/finish
    defaults: { _controller: SolidInvoice\InstallBundle\Action\Finish }
