services:
    SolidInvoice\QuoteBundle\Manager\QuoteManager:
        autowire: true
        autoconfigure: true
        arguments:
            $stateMachine: '@state_machine.quote'

    SolidInvoice\QuoteBundle\Menu\Builder:
        public: false
        tags:
            - { name: cs_core.menu, menu: sidebar, method: sidebar }

    SolidInvoice\QuoteBundle\Cloner\QuoteCloner:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.quote'

    SolidInvoice\QuoteBundle\Email\Decorator\:
        autowire: true
        resource: '../../../Email/Decorator/'
        tags: ['message.decorator']

    SolidInvoice\QuoteBundle\Repository\QuoteRepository:
        autowire: true
        tags: ['doctrine.repository_service']

    # Fixtures
    SolidInvoice\QuoteBundle\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/QuoteBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
