services:
    _defaults:
        autoconfigure: true
        autowire: true

    solidinvoice_client.menu:
        class: SolidInvoice\ClientBundle\Menu\Builder
        tags:
            - { name: 'cs_core.menu', menu: sidebar, method: sidebar }

    # Repositories
    SolidInvoice\ClientBundle\Repository\ClientRepository: ~
    SolidInvoice\ClientBundle\Repository\ContactRepository: ~
    SolidInvoice\ClientBundle\Repository\ContactTypeRepository: ~
    SolidInvoice\ClientBundle\Repository\CreditRepository: ~

    # Forms
    SolidInvoice\ClientBundle\Form\Type\ContactDetailType: ~

    # Fixtures
    SolidInvoice\ClientBundle\DataFixtures\ORM\:
        resource: '%kernel.project_dir%/src/ClientBundle/DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
