services:
    solidinvoice_menu.factory:
        class: SolidInvoice\MenuBundle\Factory
        arguments: ['@router']

    solidinvoice_menu.renderer:
        class: SolidInvoice\MenuBundle\Renderer
        arguments: ['@request_stack', '@solidinvoice_menu.factory', '@translator', '@twig']
        calls:
            - ['setContainer', ['@service_container']]

    solidinvoice_menu.provider:
        class: SolidInvoice\MenuBundle\Provider
        arguments: ['@solidinvoice_menu.storage']

    solidinvoice_menu.storage:
        class: SolidInvoice\MenuBundle\Storage\MenuStorage
