imports:
    - { resource: config_dev.yml }

parameters:
    env(database_name): solidinvoice_test

framework:
    test: true
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_test_fixtures:
    keep_database_and_schema: true
