imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: payum.yml }
    - { resource: workflow.yml }

parameters:
    container.dumper.inline_class_loader: true

framework:
    esi: null
    translator:
        fallback: en
    secret: '%env(secret)%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enabled: true
        enable_annotations: true
        email_validation_mode: html5
    default_locale: '%env(locale)%'
    session:
        name: SOLIDINVOICE_APP
    fragments: null
    http_method_override: true
    serializer: { enable_annotations: true }
    assets:
        json_manifest_path: '%kernel.project_dir%/web/static/manifest.json'

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SolidInvoiceCore/Form/fields.html.twig'

doctrine:
    dbal:
        driver: '%env(database_driver)%'
        host: '%env(database_host)%'
        port: '%env(int:database_port)%'
        dbname: '%env(database_name)%'
        user: '%env(database_user)%'
        password: '%env(database_password)%'
        charset: UTF8
        server_version: 5.5
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            money: SolidInvoice\MoneyBundle\Doctrine\Types\MoneyType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                hydrators:
                    money: SolidInvoice\MoneyBundle\Doctrine\Hydrator\MoneyHydrator
                filters:
                    archivable:
                        class: SolidInvoice\CoreBundle\Doctrine\Filter\ArchivableFilter
                        enabled: true
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                        alias: GedmoLoggable
                        is_bundle: false
                    payum:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping'
                        prefix: Payum\Core\Model

swiftmailer:
    transport: '%env(mailer_transport)%'
    host: '%env(mailer_host)%'
    username: '%env(mailer_user)%'
    password: '%env(mailer_password)%'
    encryption: '%env(mailer_encryption)%'
    port: '%env(mailer_port)%'
    spool:
        type: memory

stof_doctrine_extensions:
    default_locale: '%env(locale)%'
    orm: null

api_platform:
    title: 'API'
    version: !php/const SolidInvoice\CoreBundle\SolidInvoiceCoreBundle::VERSION
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']

webpack_encore:
    output_path: '%kernel.project_dir%/web/static'

sensio_framework_extra:
    router:
        annotations: false
