services:
    SolidInvoice\PaymentBundle\Action\:
        resource: '../../../Action'
        autowire: true
        tags: ['controller.service_arguments']

    SolidInvoice\PaymentBundle\Action\Prepare:
        autowire: true
        tags: ['controller.service_arguments']
        arguments:
            $stateMachine: '@state_machine.invoice'
