services:
    _defaults:
        autowire: true

    SolidInvoice\ApiBundle\Security\ApiTokenAuthenticator: ~
    SolidInvoice\ApiBundle\Security\Provider\ApiTokenUserProvider: ~
    SolidInvoice\ApiBundle\Event\Listener\AuthenticationSuccessHandler: ~
    SolidInvoice\ApiBundle\Event\Listener\AuthenticationFailHandler: ~
    SolidInvoice\ApiBundle\ApiTokenManager: ~

    SolidInvoice\ApiBundle\Event\Listener\InvoiceCreateListener:
        arguments:
            $stateMachine: '@state_machine.invoice'
        tags:
            - { name: 'kernel.event_subscriber' }

    SolidInvoice\ApiBundle\Event\Listener\QuoteCreateListener:
        arguments:
            $stateMachine: '@state_machine.quote'
        tags:
            - { name: 'kernel.event_subscriber' }
