services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: kernel.event_subscriber }

    SolidInvoice\InstallBundle\Listener\:
        resource: '../../../Listener/**'

    SolidInvoice\InstallBundle\Listener\RequestListener:
        arguments:
            $installed: '%env(installed)%'
            $debug: '%kernel.debug%'

    SolidInvoice\InstallBundle\Listener\UpgradeListener:
        arguments:
            $installed: '%env(installed)%'
