services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: notification.handler }

    SolidInvoice\NotificationBundle\Notification\Handler\ChainedHandler: ~
    SolidInvoice\NotificationBundle\Notification\Handler\TwilioHandler: ~
    Namshi\Notificator\Notification\Handler\SwiftMailer: ~
