services:
    _defaults:
        autowire: true

    Namshi\Notificator\Manager: ~
    Namshi\Notificator\ManagerInterface: '@Namshi\Notificator\Manager'

    SolidInvoice\NotificationBundle\Notification\NotificationManager:
    SolidInvoice\NotificationBundle\Notification\Factory: ~

    Twilio\Rest\Client:
        arguments: ['@=service(''settings'').get(''sms/twilio/sid'')', '@=service(''settings'').get(''sms/twilio/token'')']
        lazy: true
